Добавлена работа с сущностями User и Item
mkudryavtsev90/java-shareit pull request #1
Opened 2022-11-26 13:50 UTC by mkudryavtsev90

Реализованы CRUD операции для сущностей User и Item. Добавлены контроллеры.

2022-11-26 16:27 UTC, Frilock requested changes
Добрый день, сильная работа. Предложил использовать более лаконичные конструкции в паре мест, но на ваше усмотрение, если желания нет, присылайте приму и так

2022-11-26 16:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (Objects.nonNull(itemDto.getName())) {
Предлагаю заменить на Optional.ofNullable(...).ifPresent(...); будет компактнее

2022-11-26 16:27 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                if (item.getDescription().toLowerCase().contains(text.toLowerCase())
Предлагаю использовать containsIgnoreCase  от StringUtils.

2022-11-27 06:50 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (Objects.nonNull(itemDto.getName())) {
Готово

2022-11-27 06:50 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                if (item.getDescription().toLowerCase().contains(text.toLowerCase())
Готово

2022-11-27 09:15 UTC, Frilock approved these changes
Здорово, принял.

2022-11-27 13:55 UTC, merged