Add bookings
mkudryavtsev90/java-shareit pull request #2
Opened 2022-12-13 07:36 UTC by mkudryavtsev90

Добавлена поддержка JpaRepositories
Добавлена функциональность бронирования и комментариев

2022-12-13 17:54 UTC, Frilock requested changes
Добрый день, в целом все ок, пару мелких комментариев с предложениями

2022-12-13 17:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return ResponseEntity.status(201).body(createdBookingDto);
Предлагаю статусы в константу вынести

2022-12-13 17:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!booking.getStatus().equals(Status.WAITING)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2022-12-13 17:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        userRepository.findById(userId).orElseThrow(() -> {
Вынесите этот поиск в отдельный метод с название checkUserExist .... иначе в заблуждение вводит

2022-12-13 17:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookingList = bookingRepository.findByItemOwnerId(ownerId, Sort.by(Sort.Direction.DESC, "start"));
Чтобы 10 раз в методе не писать такой код, вынесите его в переменную

2022-12-13 17:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private String authorName;
А разве эти поля валедировать не надо?

2022-12-13 17:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                itemDto.getId(), LocalDateTime.now(), Sort.by(Sort.Direction.DESC, "end"));
Типы сортировок можно тоже в enum вынести

2022-12-14 08:27 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return ResponseEntity.status(201).body(createdBookingDto);
Готово

2022-12-14 08:28 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!booking.getStatus().equals(Status.WAITING)) {
Готово

2022-12-14 16:28 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        userRepository.findById(userId).orElseThrow(() -> {
Готово

2022-12-14 16:30 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private String authorName;
В json тела запроса в тестах Postman приходит только поле text, а далее мой маппер заполняет уже необходимые поля, так что не вижу что тут можно валидировать

2022-12-14 22:02 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookingList = bookingRepository.findByItemOwnerId(ownerId, Sort.by(Sort.Direction.DESC, "start"));
Не очень понял что вынести в переменную? Сортировку?

2022-12-14 22:03 UTC, mkudryavtsev90 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                itemDto.getId(), LocalDateTime.now(), Sort.by(Sort.Direction.DESC, "end"));
Вынес в константы

2022-12-15 06:28 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookingList = bookingRepository.findByItemOwnerId(ownerId, Sort.by(Sort.Direction.DESC, "start"));
Да, Sort.by(Sort.Direction.DESC, "start")

2022-12-15 06:28 UTC, Frilock approved these changes
Принято, все ок

2022-12-15 06:29 UTC, merged