Add docker
mkudryavtsev90/java-shareit pull request #4
Opened 2023-01-14 07:49 UTC by mkudryavtsev90

Приложение разделено на 2 модуля: Gateway и Server. Добавлена поддержка Docker

2023-01-14 12:45 UTC, Frilock requested changes
Добрый день, посмотрел работу,  задание в целом выполнил, все ок, но есть ряд нюансов. Я написал там общий комментарий по pom файлу, посмотри, я думаю будет полезно сделать так. Кроме того, из pom файла сервера стоит убрать зависимость на валидацию (по требованию ТЗ). Еще момент с удаленными тестами. На мой взгляд их нужно перенести в модуль gateway (возможно подправив), чтобы не терять тесты на функционал.

2023-01-14 12:45 UTC, Frilock commented on server/pom.xml
> +        <org.apache.common.commons-lang3.version>3.12.0</org.apache.common.commons-lang3.version>
Вообще какое то не очень приятное название версии, org точно не надо, common дублируется. Ну это конечно на твое усмотрение, главное чтоб понятно было

2023-01-14 12:45 UTC, Frilock commented on server/pom.xml
> +            <version>${org.mapstruct.version}</version>
Вообще я обычно такой комментарий пишу на дипломе, но напишу и тут:
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2023-01-14 12:45 UTC, Frilock commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Эта зависимость должна быть удалена, это требование ТЗ, чтобы валидация была перенесена в gateway

2023-01-14 12:45 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +    // Текущие
Смотрю на данные комментарии и думаю что вообще все же лучше их убрать (но это так, на твое усмотрение)

2023-01-14 12:45 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> -import com.fasterxml.jackson.databind.ObjectMapper;
На мой взгляд данные тесты удалять просто так не верно, их лучше тогда перенести в модуль gateway. Если есть возражения то пиши

2023-01-14 22:09 UTC, mkudryavtsev90 commented on server/pom.xml
> +        <org.apache.common.commons-lang3.version>3.12.0</org.apache.common.commons-lang3.version>
Готово

2023-01-15 05:45 UTC, mkudryavtsev90 commented on server/pom.xml
> +            <version>${org.mapstruct.version}</version>
Готово

2023-01-15 05:46 UTC, mkudryavtsev90 commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Готово

2023-01-15 05:47 UTC, mkudryavtsev90 commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +    // Текущие
Готово

2023-01-15 14:28 UTC, mkudryavtsev90 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> -import com.fasterxml.jackson.databind.ObjectMapper;
Сделано

2023-01-16 10:56 UTC, Frilock approved these changes
Здорово, принято. Успехов на дипломе

2023-01-16 13:17 UTC, merged